/**
 * This code was generated by Diez version 10.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color, File, Font, Image, Typograph } from "@diez/prefabs";

const brandArchitectureColors = {
    utilityGray: Color.rgba(131, 131, 131, 1),
    utilityBlack: Color.rgba(51, 51, 51, 1),
    veryBlack: Color.rgba(51, 51, 51, 1),
    almostBlack: Color.rgba(79, 79, 79, 1),
    paleOrange: Color.rgba(254, 204, 144, 1),
    paleBlue: Color.rgba(157, 211, 255, 1),
    almostWhite: Color.rgba(245, 247, 251, 1),
    veryWhite: Color.rgba(255, 255, 255, 1),
    harshOrange: Color.rgba(94, 255, 178, 1),
    errorRed: Color.rgba(255, 105, 97, 1),
    sucessGreen: Color.rgba(39, 174, 96, 1),
    warningYellow: Color.rgba(255, 209, 55, 1),
    shyGray: Color.rgba(230, 230, 236, 1),
    neutralGray: Color.rgba(206, 206, 212, 1),
    boldGray: Color.rgba(186, 186, 191, 1),
    notBlack: Color.rgba(130, 130, 130, 1),
    harshBlue: Color.rgba(85, 139, 255, 1),
    utilityMainColor: Color.rgba(235, 87, 87, 1),
    utilityTypeColor: Color.rgba(253, 255, 122, 1),
    utilityLigthGray: Color.rgba(246, 246, 246, 1)
};

export const brandArchitectureFonts = {
    Rubik: {
        Medium: Font.fromFile("assets/BrandArchitecture.figma.contents/fonts/Rubik-Medium.otf")
    },
    Inter: {
        SemiBold: Font.fromFile("assets/BrandArchitecture.figma.contents/fonts/Inter-SemiBold.otf"),
        Medium: Font.fromFile("assets/BrandArchitecture.figma.contents/fonts/Inter-Medium.otf"),
        Regular: Font.fromFile("assets/BrandArchitecture.figma.contents/fonts/Inter-Regular.otf")
    },
    Roboto: {
        Medium: Font.fromFile("assets/BrandArchitecture.figma.contents/fonts/Roboto-Medium.otf")
    }
};

const brandArchitectureTypography = {
    heading3: new Typograph({ letterSpacing: 0.1599999964237213, fontSize: 48, lineHeight: 72, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Rubik.Medium }),
    heading4: new Typograph({ letterSpacing: 0.25, fontSize: 40, lineHeight: 64, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Rubik.Medium }),
    heading5: new Typograph({ letterSpacing: 0, fontSize: 24, lineHeight: 40, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Inter.SemiBold }),
    heading6: new Typograph({ letterSpacing: 0.15000000596046448, fontSize: 20, lineHeight: 32, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Inter.Medium }),
    body1: new Typograph({ letterSpacing: 0.1599999964237213, fontSize: 20, lineHeight: 36, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Inter.Medium }),
    body2: new Typograph({ letterSpacing: 0.25, fontSize: 16, lineHeight: 24, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Inter.Regular }),
    button: new Typograph({ letterSpacing: 0.17500000000000002, fontSize: 14, lineHeight: 16, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Rubik.Medium }),
    caption: new Typograph({ letterSpacing: 0.4000000059604645, fontSize: 12, lineHeight: 16, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Inter.Regular }),
    overline: new Typograph({ letterSpacing: 1.5, fontSize: 10, lineHeight: 16, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Inter.Regular }),
    heading1: new Typograph({ letterSpacing: 0.16270005702972412, fontSize: 96, lineHeight: 128, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Inter.SemiBold }),
    heading2: new Typograph({ letterSpacing: 0.1599999964237213, fontSize: 64, lineHeight: 96, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Rubik.Medium }),
    subtitle1: new Typograph({ letterSpacing: 0.10000000149011612, fontSize: 16, lineHeight: 24, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Inter.Medium }),
    subtitle2: new Typograph({ letterSpacing: 0.15000000596046448, fontSize: 14, lineHeight: 24, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Inter.Medium }),
    heading31: new Typograph({ letterSpacing: 0, fontSize: 48, lineHeight: 56.25, color: Color.rgba(51, 51, 51, 1), font: new Font({ name: "WorkSans-Medium" }) }),
    heading41: new Typograph({ letterSpacing: 0.25, fontSize: 34, lineHeight: 39.84375, color: Color.rgba(51, 51, 51, 1), font: new Font({ name: "WorkSans-Regular" }) }),
    heading51: new Typograph({ letterSpacing: 0, fontSize: 24, lineHeight: 28.125, color: Color.rgba(51, 51, 51, 1), font: new Font({ name: "WorkSans-Medium" }) }),
    heading61: new Typograph({ letterSpacing: 0.15000000596046448, fontSize: 20, lineHeight: 23.4375, color: Color.rgba(51, 51, 51, 1), font: new Font({ name: "WorkSans-Medium" }) }),
    body11: new Typograph({ letterSpacing: 0.4444443881511688, fontSize: 16, lineHeight: 28, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Roboto.Medium }),
    body21: new Typograph({ letterSpacing: 0.25, fontSize: 14, lineHeight: 20, color: Color.rgba(51, 51, 51, 1), font: brandArchitectureFonts.Roboto.Medium }),
    button1: new Typograph({ letterSpacing: 0.17500000000000002, fontSize: 14, lineHeight: 16.40625, color: Color.rgba(51, 51, 51, 1), font: new Font({ name: "WorkSans-Medium" }) }),
    caption1: new Typograph({ letterSpacing: 0.4000000059604645, fontSize: 12, lineHeight: 16, color: Color.rgba(51, 51, 51, 1), font: new Font({ name: "WorkSans-Regular" }) }),
    overline1: new Typograph({ letterSpacing: 1.5, fontSize: 10, lineHeight: 16, color: Color.rgba(51, 51, 51, 1), font: new Font({ name: "WorkSans-Regular" }) }),
    heading11: new Typograph({ letterSpacing: -1.5, fontSize: 96, lineHeight: 112.5, color: Color.rgba(51, 51, 51, 1), font: new Font({ name: "WorkSans-Medium" }) }),
    heading21: new Typograph({ letterSpacing: -0.5, fontSize: 60, lineHeight: 70.3125, color: Color.rgba(51, 51, 51, 1), font: new Font({ name: "WorkSans-SemiBold" }) }),
    subtitle11: new Typograph({ letterSpacing: 0.15000000596046448, fontSize: 16, lineHeight: 24, color: Color.rgba(51, 51, 51, 1), font: new Font({ name: "WorkSans-Regular" }) }),
    subtitle21: new Typograph({ letterSpacing: 0.10000000149011612, fontSize: 14, lineHeight: 24, color: Color.rgba(51, 51, 51, 1), font: new Font({ name: "WorkSans-Medium" }) })
};

export const brandArchitectureImagesFiles = {
    icExpandMore: new File({ src: "assets/BrandArchitecture.figma.contents/images/IcExpandMore.png" }),
    icExpandMore2x: new File({ src: "assets/BrandArchitecture.figma.contents/images/IcExpandMore@2x.png" }),
    icExpandMore3x: new File({ src: "assets/BrandArchitecture.figma.contents/images/IcExpandMore@3x.png" }),
    icExpandMore4x: new File({ src: "assets/BrandArchitecture.figma.contents/images/IcExpandMore@4x.png" }),
    colorChip: new File({ src: "assets/BrandArchitecture.figma.contents/images/ColorChip.png" }),
    colorChip2x: new File({ src: "assets/BrandArchitecture.figma.contents/images/ColorChip@2x.png" }),
    colorChip3x: new File({ src: "assets/BrandArchitecture.figma.contents/images/ColorChip@3x.png" }),
    colorChip4x: new File({ src: "assets/BrandArchitecture.figma.contents/images/ColorChip@4x.png" }),
    changeThisIcon: new File({ src: "assets/BrandArchitecture.figma.contents/images/ChangeThisIcon.png" }),
    changeThisIcon2x: new File({ src: "assets/BrandArchitecture.figma.contents/images/ChangeThisIcon@2x.png" }),
    changeThisIcon3x: new File({ src: "assets/BrandArchitecture.figma.contents/images/ChangeThisIcon@3x.png" }),
    changeThisIcon4x: new File({ src: "assets/BrandArchitecture.figma.contents/images/ChangeThisIcon@4x.png" }),
    icon: new File({ src: "assets/BrandArchitecture.figma.contents/images/Icon.png" }),
    icon2x: new File({ src: "assets/BrandArchitecture.figma.contents/images/Icon@2x.png" }),
    icon3x: new File({ src: "assets/BrandArchitecture.figma.contents/images/Icon@3x.png" }),
    icon4x: new File({ src: "assets/BrandArchitecture.figma.contents/images/Icon@4x.png" }),
    iconChip: new File({ src: "assets/BrandArchitecture.figma.contents/images/IconChip.png" }),
    iconChip2x: new File({ src: "assets/BrandArchitecture.figma.contents/images/IconChip@2x.png" }),
    iconChip3x: new File({ src: "assets/BrandArchitecture.figma.contents/images/IconChip@3x.png" }),
    iconChip4x: new File({ src: "assets/BrandArchitecture.figma.contents/images/IconChip@4x.png" }),
    calendar: new File({ src: "assets/BrandArchitecture.figma.contents/images/Calendar.png" }),
    calendar2x: new File({ src: "assets/BrandArchitecture.figma.contents/images/Calendar@2x.png" }),
    calendar3x: new File({ src: "assets/BrandArchitecture.figma.contents/images/Calendar@3x.png" }),
    calendar4x: new File({ src: "assets/BrandArchitecture.figma.contents/images/Calendar@4x.png" })
};

/**
 * This is provided for backward compatibility, please use `brandArchitectureImagesFiles` instead.
 * @deprecated
 */
export const brandArchitectureComponentsFiles = brandArchitectureImagesFiles;

export const brandArchitectureImages = {
    icExpandMore: Image.responsive("assets/BrandArchitecture.figma.contents/images/IcExpandMore.png", 48, 44.41975021362305),
    colorChip: Image.responsive("assets/BrandArchitecture.figma.contents/images/ColorChip.png", 100, 150),
    changeThisIcon: Image.responsive("assets/BrandArchitecture.figma.contents/images/ChangeThisIcon.png", 24, 24),
    icon: Image.responsive("assets/BrandArchitecture.figma.contents/images/Icon.png", 24, 24),
    iconChip: Image.responsive("assets/BrandArchitecture.figma.contents/images/IconChip.png", 100, 76),
    calendar: Image.responsive("assets/BrandArchitecture.figma.contents/images/Calendar.png", 24, 24)
};

/**
 * This is provided for backward compatibility, please use `brandArchitectureImages` instead.
 * @deprecated
 */
export const brandArchitectureComponents = brandArchitectureImages;

export const brandArchitectureTokens = {
    colors: brandArchitectureColors,
    typography: brandArchitectureTypography
};
